export const inquiryConfig = {
  name: "inquiryConfig",
  title: "Inquiry Form Config",
  type: "document",
  fields: [
    {
      name: "language",
      title: "Language",
      type: "string",
      options: { list: [{ title: "English", value: "en" }, { title: "中文", value: "zh" }] },
    },
    { name: "title", title: "Section Title", type: "string" },
    { name: "subtitle", title: "Section Subtitle", type: "text" },
    { name: "partnerTitle", title: "Partner Benefits Title", type: "string" },
    {
      name: "benefits",
      title: "Partner Benefits",
      type: "array",
      of: [{ type: "string" }],
    },
    { name: "quickContact", title: "Quick Contact Label", type: "string" },
    { name: "formTitle", title: "Form Title", type: "string" },
    { name: "formSubtitle", title: "Form Subtitle", type: "string" },
    { name: "companyName", title: "Company Name Placeholder", type: "string" },
    { name: "contactName", title: "Contact Name Placeholder", type: "string" },
    { name: "email", title: "Email Placeholder", type: "string" },
    { name: "country", title: "Country Placeholder", type: "string" },
    { name: "interestedProduct", title: "Interested Product Placeholder", type: "string" },
    {
      name: "productOptions",
      title: "Product Options",
      type: "object",
      fields: [
        { name: "portable", title: "Portable", type: "string" },
        { name: "home", title: "Home ESS", type: "string" },
        { name: "commercial", title: "Commercial", type: "string" },
        { name: "oem", title: "OEM/ODM", type: "string" },
        { name: "other", title: "Other", type: "string" },
      ],
    },
    { name: "message", title: "Message Placeholder", type: "string" },
    { name: "submit", title: "Submit Button", type: "string" },
    { name: "demoNote", title: "Demo Note", type: "string" },
    { name: "emailContact", title: "Contact Email", type: "string" },
    { name: "phone", title: "Contact Phone", type: "string" },
  ],
  preview: {
    select: { language: "language" },
    prepare: ({ language }) => ({ title: `Inquiry Config - ${language === "en" ? "English" : "中文"}` }),
  },
};
